export const DISPLAY_ALERT = 'SHOW_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'

export const GRAB_EVENTS_BEGIN = 'GRAB_EVENTS_BEGIN'
export const GRAB_EVENTS_SUCCESS = 'GRAB_EVENTS_SUCCESS'
export const GRAB_EVENTS_ERROR = 'GRAB_EVENTS_ERROR'

export const REGISTER_USER_BEGIN = 'REGISTER_USER_BEGIN'
export const REGISTER_USER_SUCCESS= 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR'

export const LOGIN_USER_BEGIN = 'LOGIN_USER_BEGIN'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'

export const LOGOUT_USER = 'LOGOUT_USER'
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'

export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR'

export const HANDLE_CHANGE = 'HANDLE_CHANGE'

export const CLEAR_VALUES = 'CLEAR_VALUES'

export const CREATE_EVENT_BEGIN = 'CREATE_EVENT_BEGIN'
export const CREATE_EVENT_SUCCESS = 'CREATE_EVENT_SUCCESS'
export const CREATE_EVENT_ERROR = 'CREATE_EVENT_ERROR'

export const GET_EVENTS_BEGIN = 'GET_EVENTS_BEGIN'
export const GET_EVENTS_SUCCESS = 'GET_EVENTS_SUCCESS'

export const SET_EDIT_EVENT = 'SET_EDIT_EVENT'

export const EDIT_EVENT_BEGIN = 'EDIT_EVENT_BEGIN'
export const EDIT_EVENT_SUCCESS = 'EDIT_EVENT_SUCCESS'
export const EDIT_EVENT_ERROR = 'EDIT_EVENT_ERROR'

export const DELETE_EVENT_BEGIN = 'DELETE_EVENT_BEGIN'